clark = [
    "budget.m",
]
dallben = [
    "bazarr.m",
    "jackett.m",
    "radarr.m",
    "seerr.m",
    "sonarr.m",
    "torrents.m",
]
doli = [
    "syncthing.doli.m",
]
fflewddur = [
    "alerts.m",
    "audiobookshelf.m",
    "frigate.m",
    "grafana.m",
    "home-assistant.m",
    "immich.m",
    "immichframe.m",
    "jellyfin.m",
    "auth.m",
    "manman.m",
    "media.m",
    "miniflux.m",
    "mqtt.m",
    "ospi.m",
    "prometheus.m",
    "readeck.m",
    "ca.m",
    "syncthing.fflewddur.m",
    "vaultwarden.m",
    "whoami.m",
    "zigbee2mqtt.m",
]

