clark = [
    "clark.m",
    "budget.m",
]
dallben = [
    "dallben.m",
    "bazarr.m",
    "jackett.m",
    "radarr.m",
    "seerr.m",
    "sonarr.m",
    "torrents.m",
]
doli = [
    "doli.m",
    "syncthing.doli.m",
]
fflam = [
    "fflam.m",
]
fflewddur = [
    "fflewddur.m",
    "alerts.m",
    "audiobookshelf.m",
    "auth.m",
    "ca.m",
    "frigate.m",
    "grafana.m",
    "home-assistant.m",
    "immich.m",
    "jellyfin.m",
    "manman.m",
    "media.m",
    "miniflux.m",
    "mqtt.m",
    "ospi.m",
    "prometheus.m",
    "readeck.m",
    "syncthing.fflewddur.m",
    "vaultwarden.m",
    "whoami.m",
    "zigbee2mqtt.m",
]
jflyso = [
    "jflyso.m",
]
kent = [
    "kent.m",
]
locked-vm = [
    "locked-vm.m",
]
pattern = [
    "pattern.m",
]
template = [
    "template.m",
]
